### ISSUE TITLE
New release with python3 support

### ISSUE THREAD

**Issue by df7cb** [pgxn/pgxnclient#35]
Hi, I see that there have been python3 fixes in the repository. As Debian is removing python2 from unstable, we would need a new release with these changes so we can update the pgxnclient package.
Thanks!

**Comment by dvarrazzo** [comment]
Meh, you are right, I should have finished the release months ago...

**Comment by dvarrazzo** [comment]
pgxn 1.3 released.

**Comment by df7cb** [comment]
Thanks for the release, I've updated the Debian packages.

On a sidenote, the tarball on pypi seems to be missing the tests/testdata/ directory, so the testsuite fails because it can't find the .tar.gz files. (I've switched to the GitHub tarballs now, so it's not an issue for me.)
