### ISSUE TITLE
Test data not included in release tarballs

### ISSUE THREAD

**Issue by titanofold** [pgxn/pgxnclient#36]
Tests cannot be run with releases because the `tests\testdata` directory is missing. This, naturally, results in all tests failing.

Once I manually copy the `test\testdata`, tests pass.

**Comment by dvarrazzo** [comment]
I guess the most reasonable thing to do is to include the test data in the tarball, as opposite of excluding the tests altogether from the tarball and ask to test from git, right?

**Comment by titanofold** [comment]
(^_^) Yes, do include.

The expectation is that we can verify that the installation will work correctly.
