### ISSUE TITLE
Make options

### ISSUE THREAD

**Issue by frafra** [pgxn/pgxnclient#41]
To compile multicorn on my system, I need to specify which version of Python I want to use, like this:

```make python_version=3 && make install python_version=3```

It does not look like there is a way to add such kind of make options to pgxnclient yet.

**Comment by dvarrazzo** [comment]
No, but you can use the `--make` and point it to a wrapper, such as:

```sh
# /usr/bin/bash
exec /usr/bin/make python_version=3 "$@"
```

If there are compelling use cases to add command line support for generic make parameters, I'm happy to consider adding them.

**Comment by frafra** [comment]
That is a good solution in my opinion, thank you.
