### ISSUE TITLE
Uninstall script

### ISSUE THREAD

**Issue by beaud76** [pgxn/pgxnclient#47]
Hi,

I have a complex extension that cannot be dropped with a simple DROP EXTENSION, but needs an uninstall script. Some actions must indeed be executed before the extension drop and some others after.

I have not been able to let the pgxn client use an uninstall script instead of the regular DROP EXTENSION statement. I tried to copy the uninstall script into the $PGSHARE/$MODULEDIR directory or directly into the $PGSHARE/extension directory but unsuccessfully. May be I misread the documentation. It says in particular:

> For every extension specified in the ‘provides’ section of the distribution META.json, the command will look for a file called uninstall_file.sql where file.sql is the file specified. If no file is specified, extension.sql is assumed.

Actually, I don't understand where this `file` could be specified. I don't see a file option in the pgxn unload command and in the META.json the "file" property of the "provides" section is the file containing the extension and is not optional.

Thanks by advance for any help.

**Comment by dvarrazzo** [comment]
Hello, I aplologise for the slow delay. The internet is all broken.

I seem to remember that the file just needs to exist, not to be specified in the metadata file explicitly. This part of code seems to confirm it.

https://github.com/pgxn/pgxnclient/blob/30f75767059bd4e84b9cde477414dc24155008fe/pgxnclient/commands/install.py#L614-L618

So, I seem to remember, if the file specifies `path/to/wat.sql`, the uninstall script must be simply named `path/to/uninstall_wat.sql`.

**Comment by beaud76** [comment]
Hi
Thanks for the answer.
Reading the piece of code you pointed to me, I understand that the uninstall script is only searched when the postgres version is prior 9.1. With postgres 9.1+, the DROP EXTENSION statement is directly executed, which is not what I understand from the pgxn uninstall documentation (and is not what I would need :-)).
Am I misunderstanding something ?

**Comment by dvarrazzo** [comment]
Ah, probably yes. That's because the load script is only used for pre-EXTENSION times databases.
